version: "3.3"

services:
  openldap:
    container_name: openldap
    image: osixia/openldap:latest
    environment:
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD}
      LDAP_TLS_VERIFY_CLIENT: "never"
    volumes:
      - ./tmp/storage/openldap/ldap_db:/var/lib/ldap
      - ./tmp/storage/openldap/ldap_config:/etc/ldap/slapd.d
      - ./tmp/ldap/ldif:/container/documents
    ports:
      - "389:389"
      - "636:636"
    restart: always
    networks:
      - openldap_network
      - user_service_network

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "8083:443"
    restart: on-failure
    depends_on:
      - openldap
    networks:
      - openldap_network

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/storage/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "keycloak"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    depends_on:
      - openldap
    networks:
      - mysql_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: "mysql"
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8080:80"
    restart: on-failure
    depends_on:
      - mysql
    networks:
      - mysql_network

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - mysql
      - openldap
    networks:
      - openldap_network
      - mysql_network

  rabbitmq:
    image: "rabbitmq:latest"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - regms_network

  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin-server
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    restart: on-failure
    networks:
     - regms_network

networks:
  regms_network:
  openldap_network:
  mysql_network: