version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./volume/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "keycloak"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mysql_network

  cassandra:
    image: cassandra:latest
    container_name: my_cassandra
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "DESCRIBE keyspaces" ]
      interval: 30s
      timeout: 10s
      retries: 5

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/12345678
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./volume/neo4j/neo4j_data:/data
      - ./volume/neo4j/neo4j_logs:/logs
      - ./volume/neo4j/neo4j_import:/var/lib/neo4j/import
      - ./volume/neo4j/neo4j_plugins:/plugins

  openldap:
    container_name: openldap
    image: osixia/openldap:latest
    environment:
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD}
      LDAP_TLS_VERIFY_CLIENT: "never"
    volumes:
      - ./volume/openldap/ldap_db:/var/lib/ldap
      - ./volume/openldap/ldap_config:/etc/ldap/slapd.d
      - ./ldap/ldif:/container/documents/ldif
      - ./ldap/script:/container/documents/script
    ports:
      - "389:389"
      - "636:636"
    restart: no
    healthcheck:
      test: [ "CMD", "ldapsearch", "-H", "ldap://openldap:389", "-D", "cn=admin,dc=fayardev,dc=com", "-w", "${LDAP_ADMIN_PASSWORD}", "-b", "dc=fayardev,dc=com", "-s", "base", "(objectclass=*)" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - openldap_network
      - user_service_network

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "8083:443"
    restart: on-failure
    depends_on:
      openldap:
        condition: service_healthy
    networks:
      - openldap_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: "mysql"
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8080:80"
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mysql_network

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/realm/keycloak/realm-file.json:/opt/jboss/keycloak/standalone/configuration/realm-file.json
      - ./keycloak/theme/regms-theme:/opt/jboss/keycloak/themes/regms-theme
    depends_on:
      mysql:
        condition: service_healthy
      openldap:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://keycloak:8081/auth || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/standalone/configuration/realm-file.json"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/opt/jboss/keycloak/standalone/configuration/realm-file.json"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    networks:
      - openldap_network
      - mysql_network
      - regms_network

  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin-server
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    restart: on-failure
    networks:
      - regms_network

  config-server:
    container_name: config-server
    build:
      context: config-server
      dockerfile: Dockerfile
    environment:
      PROFILES: ${SPRING_PROFILES}
      SERVER_PORT: ${CONFIG_SERVER_PORT}
    volumes:
      - /tmp
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -S ${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}/actuator/health/readiness || exit 1" ]
      interval: 2s
      timeout: 3s
      retries: 15
    networks:
      - regms_network

  eureka-server:
    container_name: eureka-server
    build:
      context: eureka-server
      dockerfile: Dockerfile
    environment:
      PROFILES: ${EUREKA_SERVER_PROFILE}
      SERVER_PORT: ${EUREKA_SERVER_PORT}
      SERVER_HOST: ${EUREKA_SERVER_HOST}
      SERVER_URL: "${HTTP_PROTOCOL}${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}"
      CONFIG_SERVER_URL: "${HTTP_PROTOCOL}${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}"
      SPRING_BOOT_ADMIN_SERVER_URL: "${HTTP_PROTOCOL}${SPRING_BOOT_ADMIN_SERVER_HOST}:${SPRING_BOOT_ADMIN_SERVER_PORT}"
    volumes:
      - /tmp
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    healthcheck:
      test: "wget --spider -S eureka-server:${EUREKA_SERVER_PORT}/actuator/health/readiness || exit 1"
      interval: 2s
      timeout: 3s
      retries: 15
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - regms_network

  gateway-server:
    container_name: gateway-server
    build:
      context: gateway-server
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: ${GATEWAY_SERVER_PORT}
      CONFIG_SERVER_URL: "${HTTP_PROTOCOL}${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}"
      EUREKA_SERVER_URL: "${HTTP_PROTOCOL}${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}"
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      OAUTH2_RESOURCE_SERVER_JWT_ISSUER_URI: ${OAUTH2_RESOURCE_SERVER_JWT_ISSUER_URI}
    volumes:
      - /tmp
    ports:
      - "${GATEWAY_SERVER_PORT}:${GATEWAY_SERVER_PORT}"
    healthcheck:
      test: "wget --spider -S gateway-server:${GATEWAY_SERVER_PORT}/actuator/health/readiness || exit 1"
      interval: 2s
      timeout: 3s
      retries: 15
    restart: on-failure
    depends_on:
      eureka-server:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      cassandra:
        condition: service_healthy
    networks:
      - regms_network

  user-service:
    container_name: user-service
    build:
      context: user-service
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: ${USER_SERVICE_SERVER_PORT}
      CONFIG_SERVER_URL: "${HTTP_PROTOCOL}${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}"
      EUREKA_SERVER_HOST: ${EUREKA_SERVER_HOST}
      EUREKA_SERVER_URL: "${HTTP_PROTOCOL}${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}"
      LDAP_SERVER_URL: ${LDAP_SERVER_URL}
      LDAP_BASE: ${LDAP_BASE}
      LDAP_USERNAME: ${LDAP_USERNAME}
      LDAP_PASSWORD: ${LDAP_PASSWORD}
      OAUTH2_RESOURCE_SERVER_JWT_ISSUER_URI: ${OAUTH2_RESOURCE_SERVER_JWT_ISSUER_URI}
      SPRING_BOOT_ADMIN_SERVER_URL: "${HTTP_PROTOCOL}${SPRING_BOOT_ADMIN_SERVER_HOST}:${SPRING_BOOT_ADMIN_SERVER_PORT}"
      ZIPKIN_SERVER_URL: "${HTTP_PROTOCOL}${ZIPKIN_SERVER_HOST}:${ZIPKIN_SERVER_PORT}"
    volumes:
      - /tmp
    ports:
      - "${USER_SERVICE_SERVER_PORT}:${USER_SERVICE_SERVER_PORT}"
    healthcheck:
      test: "wget --spider -S user-service:${USER_SERVICE_SERVER_PORT}/actuator/health/readiness || exit 1"
      interval: 2s
      timeout: 3s
      retries: 15
    restart: on-failure
    depends_on:
      gateway-server:
        condition: service_healthy
    networks:
      - regms_network
      - user_service_network

  profile-service:
      container_name: profile-service
      build:
        context: profile-service
        dockerfile: Dockerfile
      environment:
        SERVER_PORT: ${PROFILE_SERVICE_SERVER_PORT}
        CONFIG_SERVER_URL: "${HTTP_PROTOCOL}${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}"
        EUREKA_SERVER_HOST: ${EUREKA_SERVER_HOST}
        EUREKA_SERVER_URL: "${HTTP_PROTOCOL}${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}"
        SPRING_BOOT_ADMIN_SERVER_URL: "${HTTP_PROTOCOL}${SPRING_BOOT_ADMIN_SERVER_HOST}:${SPRING_BOOT_ADMIN_SERVER_PORT}"
        ZIPKIN_SERVER_URL: "${HTTP_PROTOCOL}${ZIPKIN_SERVER_HOST}:${ZIPKIN_SERVER_PORT}"
      volumes:
        - /tmp
      ports:
        - "${PROFILE_SERVICE_SERVER_PORT}:${PROFILE_SERVICE_SERVER_PORT}"
      healthcheck:
        test: "wget --spider -S profile-service:${PROFILE_SERVICE_SERVER_PORT}/actuator/health/readiness || exit 1"
        interval: 2s
        timeout: 3s
        retries: 15
      restart: on-failure
      depends_on:
        gateway-server:
          condition: service_healthy
      networks:
        - regms_network

  post-service:
    container_name: post-service
    build:
      context: post-service
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: ${POST_SERVICE_SERVER_PORT}
      CONFIG_SERVER_URL: "${HTTP_PROTOCOL}${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}"
      EUREKA_SERVER_HOST: ${EUREKA_SERVER_HOST}
      EUREKA_SERVER_URL: "${HTTP_PROTOCOL}${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}"
      SPRING_BOOT_ADMIN_SERVER_URL: "${HTTP_PROTOCOL}${SPRING_BOOT_ADMIN_SERVER_HOST}:${SPRING_BOOT_ADMIN_SERVER_PORT}"
      ZIPKIN_SERVER_URL: "${HTTP_PROTOCOL}${ZIPKIN_SERVER_HOST}:${ZIPKIN_SERVER_PORT}"
    volumes:
      - /tmp
    ports:
      - "${POST_SERVICE_SERVER_PORT}:${POST_SERVICE_SERVER_PORT}"
    healthcheck:
      test: "wget --spider -S post-service:${POST_SERVICE_SERVER_PORT}/actuator/health/readiness || exit 1"
      interval: 2s
      timeout: 3s
      retries: 15
    restart: on-failure
    depends_on:
      gateway-server:
        condition: service_healthy
    networks:
      - regms_network

  feed-service:
    container_name: feed-service
    build:
      context: feed-service
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: ${FEED_SERVICE_SERVER_PORT}
      CONFIG_SERVER_URL: "${HTTP_PROTOCOL}${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}"
      EUREKA_SERVER_HOST: ${EUREKA_SERVER_HOST}
      EUREKA_SERVER_URL: "${HTTP_PROTOCOL}${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}"
      SPRING_BOOT_ADMIN_SERVER_URL: "${HTTP_PROTOCOL}${SPRING_BOOT_ADMIN_SERVER_HOST}:${SPRING_BOOT_ADMIN_SERVER_PORT}"
      ZIPKIN_SERVER_URL: "${HTTP_PROTOCOL}${ZIPKIN_SERVER_HOST}:${ZIPKIN_SERVER_PORT}"
    volumes:
      - /tmp
    ports:
      - "${FEED_SERVICE_SERVER_PORT}:${FEED_SERVICE_SERVER_PORT}"
    healthcheck:
      test: "wget --spider -S feed-service:${FEED_SERVICE_SERVER_PORT}/actuator/health/readiness || exit 1"
      interval: 2s
      timeout: 3s
      retries: 15
    restart: on-failure
    depends_on:
      gateway-server:
        condition: service_healthy
    networks:
      - regms_network

  follow-service:
    container_name: follow-service
    build:
      context: follow-service
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: ${FOLLOW_SERVICE_SERVER_PORT}
      CONFIG_SERVER_URL: "${HTTP_PROTOCOL}${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}"
      EUREKA_SERVER_HOST: ${EUREKA_SERVER_HOST}
      EUREKA_SERVER_URL: "${HTTP_PROTOCOL}${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}"
      SPRING_BOOT_ADMIN_SERVER_URL: "${HTTP_PROTOCOL}${SPRING_BOOT_ADMIN_SERVER_HOST}:${SPRING_BOOT_ADMIN_SERVER_PORT}"
      ZIPKIN_SERVER_URL: "${HTTP_PROTOCOL}${ZIPKIN_SERVER_HOST}:${ZIPKIN_SERVER_PORT}"
    volumes:
      - /tmp
    ports:
      - "${FOLLOW_SERVICE_SERVER_PORT}:${FOLLOW_SERVICE_SERVER_PORT}"
    healthcheck:
      test: "wget --spider -S follow-service:${FOLLOW_SERVICE_SERVER_PORT}/actuator/health/readiness || exit 1"
      interval: 2s
      timeout: 3s
      retries: 15
    restart: on-failure
    depends_on:
      gateway-server:
        condition: service_healthy
    networks:
      - regms_network

  admin-server:
    container_name: admin-server
    build:
      context: admin-server
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: ${SPRING_BOOT_ADMIN_SERVER_PORT}
      CONFIG_SERVER_URL: "${HTTP_PROTOCOL}${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}"
      EUREKA_SERVER_URL: "${HTTP_PROTOCOL}${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}"
    volumes:
      - /tmp
    ports:
      - "${SPRING_BOOT_ADMIN_SERVER_PORT}:${SPRING_BOOT_ADMIN_SERVER_PORT}"
    healthcheck:
      test: "wget --spider -S admin-server:${SPRING_BOOT_ADMIN_SERVER_PORT}/actuator/health/readiness || exit 1"
      interval: 2s
      timeout: 3s
      retries: 15
    restart: no
    depends_on:
      gateway-server:
        condition: service_healthy
    networks:
      - regms_network

networks:
  regms_network:
  user_service_network:
  openldap_network:
  mysql_network: