server:
  port: ${EUREKA_SERVER_PORT:8761}
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8077}

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"