server:
  port: ${FILE_SERVICE_SERVER_PORT:8083}
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8077}

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka/

spring:
  application:
    name: file-server
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}

springdoc:
  packagesToScan: com.fayardev.regms.fileserver

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"