server:
  port: ${SERVER_PORT:0}
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8077}

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka/

spring:
  application:
    name: follow-service
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}

springdoc:
  packagesToScan: com.fayardev.regms.followservice

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"