server:
  port: ${SERVER_PORT:8084}

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}

spring:
  application:
    name: follow-service
  zipkin:
    base-url: http://localhost:9411

springdoc:
  packagesToScan: com.fayardev.regms.followservice

management:
  tracing:
    sampling:
      probability: 1.0