server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8500}/eureka/
    register-with-eureka: false
  instance:
    preferIpAddress: true

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**