server:
  port: ${SERVER_PORT:0}
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8077}

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka/

spring:
  application:
    name: profile-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCE_SERVER_JWT_ISSUER_URI:http://localhost:8080/auth/realms/regms}
  data:
    cassandra:
      keyspace: regms_profile
      contact-points: ${CASSANDRA_CONTACT_POINTS:127.0.0.1}
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}

springdoc:
  packagesToScan: com.fayardev.regms.profileservice

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"