server:
  port: ${SERVER_PORT:8087}

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}

spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/regms
  zipkin:
    base-url: http://localhost:9411
  ldap:
    urls: ldap://localhost:389
    base: dc=fayardev,dc=com
    username: cn=admin,dc=fayardev,dc=com
    password: admin

springdoc:
  packagesToScan: com.fayardev.regms.userservice

management:
  tracing:
    sampling:
      probability: 1.0