server:
  port: ${SERVER_PORT:0}
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8077}

grpc:
  server:
    port: 0

eureka:
  instance:
    metadata-map:
      grpc.port: ${grpc.server.port:0}
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka/

spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCE_SERVER_JWT_ISSUER_URI:http://localhost:8081/auth/realms/regms}
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}
  sleuth:
    sampler:
      probability: 1.0
  ldap:
    urls: ${LDAP_SERVER_URL:ldap://localhost:389}
    base: ${LDAP_BASE:dc=fayardev,dc=com}
    username: ${LDAP_USERNAME:cn=admin},dc=fayardev,dc=com
    password: ${LDAP_PASSWORD:admin}

springdoc:
  packagesToScan: com.fayardev.regms.userservice

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true